[mesh]
path = "resources/test_my_animation"
animated = true

[material]
kd = [0.5, 0.5, 0.5]
ks = [0.5, 0.5, 0.5]
shininess = 3.0
toonDiscretize = 4.0
toonSpecularThreshold = 0.49

[lights]
positions = [[1.0, 20.0, -2.0]]
colors = [[1.0, 0.9, 1.0]]
is_spotlight = [false]
direction = [[0.707, 0.0, 0.707]]
has_texture = [false]
texture_path = ["resources/smiley.png"]


[camera]
lookAt = [0.0, 0.0, -1.0]
rotations = [0.0, 0.0, 0.0]
dist = 5.0
fovy = 50.0

[render_settings]
diffuse_model = "lambert" # or "debug" or "toon" or "x-toon"
specular_model = "blinn-phong" # or "phong" or "blinn-phong" or "toon"
shadows = false # or false
pcf = false # or false